services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
      - ./server/.env.development
    networks:
      - network

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_SERVER_URL: http://localhost:3000
        VITE_WS_URL: ws://localhost:3000
        REPOSITORY_URL: https://github.com/bberkay/chess
    ports:
      - "4173:4173"
    depends_on:
      - server
    networks:
      - network

networks:
  network:
    driver: bridge
